// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public interface HumidStatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.HumidStatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 response = 1;</code>
   */
  long getResponse();
}
