// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public interface LightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.LightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 request = 1;</code>
   */
  long getRequest();
}
