// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public final class Service2Impl {
  private Service2Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_TempRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_TempRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_TempResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_TempResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_HumidRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_HumidRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_HumidResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_HumidResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_LightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_LightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_LightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_LightResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_TempStatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_TempStatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_TempStatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_TempStatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_HumidStatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_HumidStatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_HumidStatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_HumidStatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_LightStatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_LightStatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_LightStatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_LightStatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service2.proto\022\010service2\"\036\n\013TempReques" +
      "t\022\017\n\007request\030\001 \001(\003\"\037\n\014TempResponse\022\017\n\007re" +
      "ponse\030\001 \001(\003\"\037\n\014HumidRequest\022\017\n\007request\030\001" +
      " \001(\003\"!\n\rHumidResponse\022\020\n\010response\030\001 \001(\003\"" +
      "\037\n\014LightRequest\022\017\n\007request\030\001 \001(\003\"!\n\rLigh" +
      "tResponse\022\020\n\010response\030\001 \001(\003\"\"\n\017TempStatR" +
      "equest\022\017\n\007request\030\001 \001(\t\"#\n\020TempStatRespo" +
      "nse\022\017\n\007reponse\030\001 \001(\003\"#\n\020HumidStatRequest" +
      "\022\017\n\007request\030\001 \001(\t\"%\n\021HumidStatResponse\022\020" +
      "\n\010response\030\001 \001(\003\"#\n\020LightStatRequest\022\017\n\007" +
      "request\030\001 \001(\t\"%\n\021LightStatResponse\022\020\n\010re" +
      "sponse\030\001 \001(\0032\311\003\n\010Service2\022C\n\014tempModifie" +
      "r\022\025.service2.TempRequest\032\026.service2.Temp" +
      "Response\"\000(\0010\001\022F\n\rhumidModifier\022\026.servic" +
      "e2.HumidRequest\032\027.service2.HumidResponse" +
      "\"\000(\0010\001\022F\n\rlightModifier\022\026.service2.Light" +
      "Request\032\027.service2.LightResponse\"\000(\0010\001\022J" +
      "\n\017tempStatusCheck\022\031.service2.TempStatReq" +
      "uest\032\032.service2.TempStatResponse\"\000\022M\n\020hu" +
      "midStatusCheck\022\032.service2.HumidStatReque" +
      "st\032\033.service2.HumidStatResponse\"\000\022M\n\020lig" +
      "htStatusCheck\022\032.service2.LightStatReques" +
      "t\032\033.service2.LightStatResponse\"\000B\035\n\013ds.s" +
      "ervice2B\014Service2ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service2_TempRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service2_TempRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_TempRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_service2_TempResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service2_TempResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_TempResponse_descriptor,
        new java.lang.String[] { "Reponse", });
    internal_static_service2_HumidRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service2_HumidRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_HumidRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_service2_HumidResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service2_HumidResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_HumidResponse_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_service2_LightRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_service2_LightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_LightRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_service2_LightResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_service2_LightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_LightResponse_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_service2_TempStatRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_service2_TempStatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_TempStatRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_service2_TempStatResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_service2_TempStatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_TempStatResponse_descriptor,
        new java.lang.String[] { "Reponse", });
    internal_static_service2_HumidStatRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_service2_HumidStatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_HumidStatRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_service2_HumidStatResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_service2_HumidStatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_HumidStatResponse_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_service2_LightStatRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_service2_LightStatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_LightStatRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_service2_LightStatResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_service2_LightStatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_LightStatResponse_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
