// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public interface TempResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.TempResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 reponse = 1;</code>
   */
  long getReponse();
}
