// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public interface SensorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service3.SensorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool noDisturbance = 1;</code>
   */
  boolean getNoDisturbance();
}
