// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package ds.service3;

public final class Service3Impl {
  private Service3Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_SensorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_SensorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_SensorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_SensorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_SensorLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_SensorLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service3_SensorLogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service3_SensorLogResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service3.proto\022\010service3\"&\n\rSensorRequ" +
      "est\022\025\n\rnoDisturbance\030\001 \001(\010\"\"\n\016SensorResp" +
      "onse\022\020\n\010response\030\001 \001(\t\"#\n\020SensorLogReque" +
      "st\022\017\n\007request\030\001 \001(\t\"%\n\021SensorLogResponse" +
      "\022\020\n\010response\030\001 \001(\t2\240\001\n\010Service3\022E\n\014motio" +
      "nSensor\022\027.service3.SensorRequest\032\030.servi" +
      "ce3.SensorResponse\"\000(\001\022M\n\016sensorLogCheck" +
      "\022\032.service3.SensorLogRequest\032\033.service3." +
      "SensorLogResponse\"\0000\001B\035\n\013ds.service3B\014Se" +
      "rvice3ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service3_SensorRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service3_SensorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_SensorRequest_descriptor,
        new java.lang.String[] { "NoDisturbance", });
    internal_static_service3_SensorResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service3_SensorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_SensorResponse_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_service3_SensorLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service3_SensorLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_SensorLogRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_service3_SensorLogResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service3_SensorLogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service3_SensorLogResponse_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
