// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public interface EntryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.EntryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool authorised = 1;</code>
   */
  boolean getAuthorised();
}
