// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public final class Service1Impl {
  private Service1Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_EntryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_EntryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_EntryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_EntryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_EntryLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_EntryLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service1_EntryLogResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service1_EntryLogResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service1.proto\022\010service1\"\037\n\014EntryReque" +
      "st\022\017\n\007request\030\001 \001(\t\"#\n\rEntryResponse\022\022\n\n" +
      "authorised\030\001 \001(\010\"\"\n\017EntryLogRequest\022\017\n\007r" +
      "equest\030\001 \001(\t\"$\n\020EntryLogResponse\022\020\n\010resp" +
      "onse\030\001 \001(\t2\233\001\n\010Service1\022C\n\016authoriseEntr" +
      "y\022\026.service1.EntryRequest\032\027.service1.Ent" +
      "ryResponse\"\000\022J\n\rentryLogCheck\022\031.service1" +
      ".EntryLogRequest\032\032.service1.EntryLogResp" +
      "onse\"\0000\001B\035\n\013ds.service1B\014Service1ImplP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service1_EntryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service1_EntryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_EntryRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_service1_EntryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service1_EntryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_EntryResponse_descriptor,
        new java.lang.String[] { "Authorised", });
    internal_static_service1_EntryLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service1_EntryLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_EntryLogRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_service1_EntryLogResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service1_EntryLogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service1_EntryLogResponse_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
